services:
  db:
    image: mysql:8.0.39
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ijb
      MYSQL_USER: dba
      MYSQL_PASSWORD: 123456