version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/ijb
      DATABASE_USER: dba
      DATABASE_PASS: 123456
      JWT-SECRET-KEY: 1nSt1Tut0J0@4oD3B@rr0Un1F4c3fC0mp
      HOST: http://localhost:5173
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ijb
      MYSQL_USER: dba
      MYSQL_PASSWORD: 123456
